### ISSUE TITLE
Support passing in a custom Ajv instance

### ISSUE THREAD

**Issue by felixfbecker** [fastify/fastify-response-validation#93]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Please provide the ability to pass in your own Ajv instance.

### Motivation

Currently, one can only pass in `ajv` options, and the plugin instantiates `ajv`.
But to use latest drafts of JSON Schema, one has to import a different `Ajv` class than the default export: https://ajv.js.org/json-schema.html#draft-2020-12

In Fastify request validation, this is possible with `setCompileFactory()`, but it won't work for response validation.

### Example

```ts
const ajv = new Ajv2020({ ... })
fastify.register(responseValidation, { ajv })
```

**Comment by Fdawgs** [comment]
Closed by #94
